import { test } from '@playwright/test';
import { AuthApi } from '../../src/api/AuthApi';
import { AuthFlow } from '../../src/flows/AuthFlow';
import { generateWallet, type EvmWalletType, type WalletInfo } from '../../src/utils/walletMock';

/**
 * One-time setup script: creates test accounts on production and prints
 * credentials for .env.prod. Run once, then copy output into .env.prod.
 *
 * Usage:
 *   ENV_FILE=.env.prod npx playwright test tests/production/setup.spec.ts --project=production
 */

// test.describe.serial('Production account setup', () => {
//   const credentials: string[] = [];
//   const password = process.env.USER_PASSWORD!;

//   let emailUser: { email: string; username: string };
//   const walletUsers: { type: EvmWalletType; label: string; envPrefix: string; wallet: WalletInfo; username: string }[] = [];

//   const walletConfigs: { type: EvmWalletType; label: string; envPrefix: string }[] = [
//     { type: 'metamask', label: 'MetaMask', envPrefix: 'PROD_WALLET_METAMASK' },
//     { type: 'hero-wallet', label: 'Hero Wallet', envPrefix: 'PROD_WALLET_HERO' },
//     { type: 'binance-wallet', label: 'Binance Wallet', envPrefix: 'PROD_WALLET_BINANCE' },
//   ];

//   test('Create email user via API', async ({ page, request }) => {
//     const authApi = new AuthApi(request);
//     const authFlow = new AuthFlow(page);

//     await test.step('Create and verify user', async () => {
//       emailUser = await authApi.createAndVerifyUser();
//     });

//     await test.step('Login to confirm account works', async () => {
//       await authFlow.loginSuccess(emailUser.email, password, emailUser.username);
//     });

//     await test.step('Logout', async () => {
//       await authFlow.logout();
//     });

//     credentials.push(
//       `PROD_TEST_EMAIL=${emailUser.email}`,
//       `PROD_TEST_PASSWORD=${password}`,
//       `PROD_TEST_USERNAME=${emailUser.username}`,
//     );
//   });

//   for (const cfg of walletConfigs) {
//     test(`Register ${cfg.label} wallet user`, async ({ page }) => {
//       const authFlow = new AuthFlow(page);
//       const wallet = generateWallet();

//       await test.step(`Register with ${cfg.label}`, async () => {
//         const result = await authFlow.walletRegisterSuccess({ wallet, walletType: cfg.type });
//         walletUsers.push({ ...cfg, wallet: result.wallet, username: result.username });

//         credentials.push(
//           `${cfg.envPrefix}_ADDRESS=${result.wallet.address}`,
//           `${cfg.envPrefix}_PRIVATE_KEY=${result.wallet.privateKey}`,
//           `${cfg.envPrefix}_USERNAME=${result.username}`,
//         );
//       });

//       await test.step('Logout', async () => {
//         await authFlow.logout();
//       });
//     });
//   }

//   test('Print credentials for .env.prod', async () => {
//     console.log('\n');
//     console.log('='.repeat(50));
//     console.log('=== COPY THE LINES BELOW TO .env.prod ===');
//     console.log('='.repeat(50));
//     console.log('');
//     console.log('# Pre-created test accounts (generated by setup.spec.ts)');
//     for (const line of credentials) {
//       console.log(line);
//     }
//     console.log('');
//     console.log('='.repeat(50));
//     console.log('\n');
//   });
// });
